name: Compile Apps
on: [workflow_dispatch, workflow_call]

jobs:
  check-types:
    strategy:
      matrix:
        directory: [ "app", "api", "front" ]
    name: Validate TypeScript
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ./apps/api/node_modules
            ./apps/app/node_modules
            ./apps/front/node_modules
            ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - run: npm run check-types
        working-directory: ./apps/${{matrix.directory}}
        name: Checking TypeScript
